### ISSUE TITLE
roomshop.js error

### ISSUE THREAD

**Issue by MeliodasBH** [MeliodasBH/Potato#12]
Error Message:

/root/Potato/chat-plugins/roomshop.js:15
currencyName: function (_cost){
              ^^^^^^^^

SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/root/Potato/command-parser.js:57:26)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
root@boarhat:~/Potato#

Code can be found at http://pastebin.com/MhgB0RLk

**Comment by Conbeef** [comment]
Remove that function and it should work
