### ISSUE TITLE
Login Issues?

### ISSUE THREAD

**Issue by MeliodasBH** [MeliodasBH/Potato#15]
CRASH: TypeError: this.poll.updateFor is not a function
    at Room.GlobalRoom.GlobalRoom.roomid.writeNumRooms.ChatRoom.rollLogFile.ChatRoom.onRename (/root/Potato/rooms.js:1547:63)
    at User.forceRename (/root/Potato/users.js:939:13)
    at User.handleRename (/root/Potato/users.js:870:12)
    at User.validateRename (/root/Potato/users.js:805:8)
    at Object.<anonymous> (/root/Potato/users.js:741:10)
    at ChildProcess.<anonymous> (/root/Potato/verifier.js:35:28)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:695:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)

**Comment by MeliodasBH** [comment]
http://pastebin.com/12VvzTmz
